const PRODUCT_IMAGES = {
  'intel-x6425': ['assets/images/intelx6425.png'],
  'inv-ce-xx':   ['assets/images/inv-ce-xx.png'],
  'inv-cea-xx':  ['assets/images/inv-cea-xx.png'],
  'inv-ceb-xx':  ['assets/images/inv-ceb-xx.png'],
  'inv-cd-xx':   ['assets/images/inv-cd-xx-1.png', 'assets/images/inv-cd-xx-2.png'],
  'rtsxx':       ['assets/images/rts-xx-1.png', 'assets/images/rts-xx-2.png'],
  'ru60':        ['assets/images/ru60.png'],
  'roxx':        ['assets/images/ro-xx.png'],
  'rtxx':        ['assets/images/rt-xx.png'],
  'rvxx':        ['assets/images/rv-xx.png'],
  'rv00':        ['assets/images/rv00.png'],
  'rdxx':        ['assets/images/rd-xx.png'],
  'rexx':        ['assets/images/re-xx.png'],
  'ri44':        ['assets/images/ri44.png'],
  'mt7621odu':   ['assets/images/MT7621-01 ODU.png'],
  'rt65odu':     ['assets/images/RT65-ODU.png'],
  'idf':         ['assets/images/idf.png'],
  'iexx':        ['assets/images/iexx-x-xx.png'],
  'iaxx':        ['assets/images/iaxx-x.png'],
  'rfnxx':       ['assets/images/rfn-xx.png'],
  'iabxx':       ['assets/images/iab-xx-x.png'],
  'iacxx':       ['assets/images/iac-xx-x.png'],
  'iafxx':       ['assets/images/iaf-xx-x.png'],
  'idxx':        ['assets/images/idxx-x.png'],
  'idbxx':       ['assets/images/idb-xx-x.png'],
  'isense':      ['assets/images/isense-violet.png'],
  'xa82':        ['assets/images/xa-82-2.png'],
  'xb82':        ['assets/images/xb-82-2.png'],
  'xc80':        ['assets/images/xc-80-1.png'],
  'xd50':        ['assets/images/xd-50-1.png'],
  'xf100':       ['assets/images/xf-100-1.png'],
  'xg82':        ['assets/images/xg-82-2l.png'],
  'pc3xx':       ['assets/images/pc3-xx.png'],
  'mcx':         ['assets/images/mc-x.png'],
  'rn50pcba':    ['assets/images/RN50-PCB-A.png'],
  'rvw50':       ['assets/images/RVW 50-M12.png'],
  'miniups':     ['assets/images/Mini UPS.png'],
  'multimeter':  ['assets/images/Multi Function Meter.png', 'assets/images/Multi Function Meter-2.png'],
  'dcmeter':     ['assets/images/DC Meter-1.png', 'assets/images/DC Meter-2.png'],
  'acmeter':     ['assets/images/AC Meter-1.png', 'assets/images/AC Meter-2.png'],
  'bcpmeter':    ['assets/images/Branch Circuit Power Meter.png'],
  'nms':         ['assets/images/NMS.jpg']
};

const PRODUCT_USE_CASES = {
  'intel-x6425': ['Edge Computing', '5G Connectivity Hub', 'Video Analytics', 'SD-WAN Aggregator'],
  'inv-ce-xx':   ['SD-WAN Gateway', 'Branch Office Router', 'Edge Compute Node', 'IoT Data Hub'],
  'inv-cea-xx':  ['Industrial PC Gateway', 'SCADA Integration', 'Smart Factory Edge', 'Multi-protocol Bridge'],
  'inv-ceb-xx':  ['Multi-WAN Aggregation', 'High-Availability SD-WAN', 'Dual 5G Redundancy', 'Data Center Edge'],
  'inv-cd-xx':   ['Digital Kiosk / HMI', 'Edge Mini-PC', 'Video Wall Controller', 'Industrial Desktop'],
  'rtsxx':       ['Industrial Site Connectivity', 'Remote Site Monitoring', 'Smart Grid Backhaul', 'WAN Redundancy'],
  'ru60':        ['Indoor Wi-Fi Coverage', 'Office Hotspot', 'Wi-Fi Mesh Extension', 'Guest Network'],
  'roxx':        ['WAN Load Balancing', 'Branch Office Failover', 'Campus Mesh Network', 'Multi-WAN Hub'],
  'rtxx':        ['Remote Site Connectivity', 'Industrial IoT', 'Temporary Site Networks', 'Machine-to-Cloud'],
  'rvxx':        ['Remote Asset Monitoring', 'Industrial IoT Connectivity', 'Utility Metering', 'Vending Machine Networks'],
  'rv00':        ['Secure Isolated Networks', 'Local LAN Routing', 'Industrial Control Segments', 'Wired Edge Router'],
  'rdxx':        ['SCADA / Modbus Gateway', 'Meter Data Collection', 'PLC Connectivity', 'Industrial Data Bridge'],
  'rexx':        ['Retail POS Connectivity', 'ATM / Banking Terminals', 'Kiosk Networking', 'Small Branch WAN'],
  'ri44':        ['Telecom Tower Backhaul', 'Street Cabinet Networking', '-48V Plant Equipment', 'RS485 Serial Gateway'],
  'mt7621odu':   ['Outdoor CCTV Connectivity', 'Smart Street Lighting', 'Outdoor Sensor Nodes', 'Billboard Networking'],
  'rt65odu':     ['Outdoor Industrial 5G', 'Construction Site Networks', 'Stadium / Events', 'Port / Logistics Yard'],
  'idf':         ['Telecom Tower Equipment', '-48V Telecom Plant', 'Base Station Backhaul', 'RS485 Serial Integration'],
  'iexx':        ['Smart Meter Reading', 'Remote Sensor Data', 'Asset Tracking', 'Building Automation'],
  'iaxx':        ['Automatic Meter Reading', 'Environmental Monitoring', 'Industrial Sensor Gateway', 'Smart Grid AMI'],
  'rfnxx':       ['Alarm / Security Systems', 'Door & Gate Control', 'Digital I/O Monitoring', 'Field Automation'],
  'iabxx':       ['SCADA Data Aggregation', 'Process Monitoring', 'Multi-protocol Integration', 'Industrial Control Gateway'],
  'iacxx':       ['Local Device Networking', 'Multi-device Industrial Hub', 'Edge IoT Gateway', 'Field Controller'],
  'iafxx':       ['Energy Sub-metering', 'Utility Infrastructure', 'Telecom Power Monitoring', 'Genset / UPS Monitoring'],
  'idxx':        ['Smart Building Automation', 'HVAC Control', 'Access Control Systems', 'Industrial IoT Hub'],
  'idbxx':       ['Industrial Machine Monitoring', 'Production Line Data', 'Process Automation', 'Heavy I/O Control'],
  'isense':      ['Telecom Tower Monitoring', 'Industrial RTU / PLC', 'Building Management', 'Substation Automation', 'SCADA Remote Terminal'],
  'xa82':        ['IP Camera Networks', 'VoIP Deployment', 'Access Point Powering', 'Industrial PoE Switching'],
  'xb82':        ['Industrial Network Backbone', 'Server Room Switching', 'Edge Aggregation', 'Gigabit Fiber Uplink'],
  'xc80':        ['Small IP Camera Systems', 'PoE Device Connectivity', 'Industrial Field Devices', 'DIN Rail PoE Switch'],
  'xd50':        ['Compact PoE Deployment', 'Single Cabinet Networking', 'Small Device Clusters', 'Edge PoE Switching'],
  'xf100':       ['Large IP Camera Deployments', 'Industrial Sensor Networks', 'High-Port-Count PoE', 'PoE Device Hub'],
  'xg82':        ['Managed Enterprise Networks', 'VLAN Segmentation', 'QoS-Critical Applications', 'IT/OT Convergence'],
  'pc3xx':       ['Legacy RS485 Integration', 'Modbus TCP Conversion', 'SCADA Serial-to-IP Bridge', 'Industrial Protocol Gateway'],
  'mcx':         ['Long-Distance Fiber Link', 'Building-to-Building Network', 'Campus Fiber Extension', 'Fiber Backhaul'],
  'rn50pcba':    ['Vehicle / Rolling Stock Networking', 'Embedded System Integration', 'Harsh Environment Deployment', 'M12 Ruggedized Networks'],
  'rvw50':       ['Railcar / Train Wi-Fi', 'Agricultural Machinery', 'Marine / Vessel Networking', 'Military Vehicle Comms'],
  'nms':         ['ISP Router Management', 'Smart City IoT Gateways', 'Enterprise Network Monitoring', 'Energy & Infrastructure Remote Sites'],
  'miniups':     ['Router Power Backup', 'Industrial Device Continuity', 'Remote Site Power Resilience', 'Gateway Failover Power'],
  'multimeter':  ['Energy Auditing', 'Building Energy Management', 'Industrial Power Monitoring', 'Utility Sub-metering'],
  'dcmeter':     ['Solar PV Monitoring', 'Battery System Monitoring', 'DC Plant Energy Metering', 'Telecom Power Monitoring'],
  'acmeter':     ['AC Distribution Monitoring', 'Motor Current Monitoring', 'Power Quality Analysis', 'Generator Output Metering'],
  'bcpmeter':    ['Panel-Level Energy Sub-metering', 'Data Center PDU Monitoring', 'Building Electrical Audit', 'Branch Circuit Monitoring'],
};
