const PRODUCT_IMAGES = {
  'intel-x6425': ['assets/images/intelx6425.png'],
  'inv-ce-xx':   ['assets/images/inv-ce-xx.png'],
  'inv-cea-xx':  ['assets/images/inv-cea-xx.png'],
  'inv-ceb-xx':  ['assets/images/inv-ceb-xx.png'],
  'inv-cd-xx':   ['assets/images/inv-cd-xx-1.png', 'assets/images/inv-cd-xx-2.png'],
  'rtsxx':       ['assets/images/rts-xx-1.png', 'assets/images/rts-xx-2.png'],
  'ru60':        ['assets/images/ru60.png'],
  'roxx':        ['assets/images/ro-xx.png'],
  'rtxx':        ['assets/images/rt-xx.png'],
  'rvxx':        ['assets/images/rv-xx.png'],
  'rv00':        ['assets/images/rv00.png'],
  'rdxx':        ['assets/images/rd-xx.png'],
  'rexx':        ['assets/images/re-xx.png'],
  'ri44':        ['assets/images/ri44.png'],
  'mt7621odu':   ['assets/images/MT7621-01 ODU.png'],
  'rt65odu':     ['assets/images/RT65-ODU.png'],
  'idfxx':       ['assets/images/idf-xx.png'],
  'iexx':        ['assets/images/iexx-x-xx.png'],
  'iaxx':        ['assets/images/iaxx-x.png'],
  'rfnxx':       ['assets/images/rfn-xx.png'],
  'iabxx':       ['assets/images/iab-xx-x.png'],
  'iacxx':       ['assets/images/iac-xx-x.png'],
  'iafxx':       ['assets/images/iaf-xx-x.png'],
  'idxx':        ['assets/images/idxx-x.png'],
  'idbxx':       ['assets/images/idb-xx-x.png'],
  'isense':      ['assets/images/isense-violet.png'],
  'xa82':        ['assets/images/xa-82-2.png'],
  'xb82':        ['assets/images/xb-82-2.png'],
  'xc80':        ['assets/images/xc-80-1.png'],
  'xd50':        ['assets/images/xd-50-1.png'],
  'xf100':       ['assets/images/xf-100-1.png'],
  'xg82':        ['assets/images/xg-82-2l.png'],
  'pc3xx':       ['assets/images/pc3-xx.png'],
  'mcx':         ['assets/images/mc-x.png'],
  'rn50pcba':    ['assets/images/RN50-PCB-A.png'],
  'rvw50':       ['assets/images/RVW 50-M12.png'],
  'miniups':     ['assets/images/Mini UPS.png'],
  'multimeter':  ['assets/images/Multi Function Meter.png', 'assets/images/Multi Function Meter-2.png'],
  'dcmeter':     ['assets/images/DC Meter-1.png', 'assets/images/DC Meter-2.png'],
  'acmeter':     ['assets/images/AC Meter-1.png', 'assets/images/AC Meter-2.png'],
  'bcpmeter':    ['assets/images/Branch Circuit Power Meter.png'],
  'nms':         ['assets/images/NMS.jpg']
};

const PRODUCT_USE_CASES = {
  'intel-x6425': ['Edge Computing', '5G Connectivity Hub', 'Video Analytics', 'SD-WAN Aggregator'],
  'inv-ce-xx':   ['SD-WAN Gateway', 'Branch Office Router', 'Edge Compute Node', 'IoT Data Hub'],
  'inv-cea-xx':  ['Industrial PC Gateway', 'SCADA Integration', 'Smart Factory Edge', 'Multi-protocol Bridge'],
  'inv-ceb-xx':  ['Multi-WAN Aggregation', 'High-Availability SD-WAN', 'Dual 5G Redundancy', 'Data Center Edge'],
  'inv-cd-xx':   ['Digital Kiosk / HMI', 'Edge Mini-PC', 'Video Wall Controller', 'Industrial Desktop'],
  'rtsxx':       ['Industrial Site Connectivity', 'Remote Site Monitoring', 'Smart Grid Backhaul', 'WAN Redundancy'],
  'ru60':        ['Indoor Wi-Fi Coverage', 'Office Hotspot', 'Wi-Fi Mesh Extension', 'Guest Network'],
  'roxx':        ['WAN Load Balancing', 'Branch Office Failover', 'Campus Mesh Network', 'Multi-WAN Hub'],
  'rtxx':        ['Remote Site Connectivity', 'Industrial IoT', 'Temporary Site Networks', 'Machine-to-Cloud'],
  'rvxx':        ['Remote Asset Monitoring', 'Industrial IoT Connectivity', 'Utility Metering', 'Vending Machine Networks'],
  'rv00':        ['Secure Isolated Networks', 'Local LAN Routing', 'Industrial Control Segments', 'Wired Edge Router'],
  'rdxx':        ['SCADA / Modbus Gateway', 'Meter Data Collection', 'PLC Connectivity', 'Industrial Data Bridge'],
  'rexx':        ['Retail POS Connectivity', 'ATM / Banking Terminals', 'Kiosk Networking', 'Small Branch WAN'],
  'ri44':        ['Telecom Tower Backhaul', 'Street Cabinet Networking', '-48V Plant Equipment', 'RS485 Serial Gateway'],
  'mt7621odu':   ['Outdoor CCTV Connectivity', 'Smart Street Lighting', 'Outdoor Sensor Nodes', 'Billboard Networking'],
  'rt65odu':     ['Outdoor Industrial 5G', 'Construction Site Networks', 'Stadium / Events', 'Port / Logistics Yard'],
  'idfxx':       ['Telecom Tower Equipment', '-48V Telecom Plant', 'Base Station Backhaul', 'RS485 Serial Integration'],
  'iexx':        ['Smart Meter Reading', 'Remote Sensor Data', 'Asset Tracking', 'Building Automation'],
  'iaxx':        ['Automatic Meter Reading', 'Environmental Monitoring', 'Industrial Sensor Gateway', 'Smart Grid AMI'],
  'rfnxx':       ['Alarm / Security Systems', 'Door & Gate Control', 'Digital I/O Monitoring', 'Field Automation'],
  'iabxx':       ['SCADA Data Aggregation', 'Process Monitoring', 'Multi-protocol Integration', 'Industrial Control Gateway'],
  'iacxx':       ['Local Device Networking', 'Multi-device Industrial Hub', 'Edge IoT Gateway', 'Field Controller'],
  'iafxx':       ['Energy Sub-metering', 'Utility Infrastructure', 'Telecom Power Monitoring', 'Genset / UPS Monitoring'],
  'idxx':        ['Smart Building Automation', 'HVAC Control', 'Access Control Systems', 'Industrial IoT Hub'],
  'idbxx':       ['Industrial Machine Monitoring', 'Production Line Data', 'Process Automation', 'Heavy I/O Control'],
  'isense':      ['Telecom Tower Monitoring', 'Industrial RTU / PLC', 'Building Management', 'Substation Automation', 'SCADA Remote Terminal'],
  'xa82':        ['IP Camera Networks', 'VoIP Deployment', 'Access Point Powering', 'Industrial PoE Switching'],
  'xb82':        ['Industrial Network Backbone', 'Server Room Switching', 'Edge Aggregation', 'Gigabit Fiber Uplink'],
  'xc80':        ['Small IP Camera Systems', 'PoE Device Connectivity', 'Industrial Field Devices', 'DIN Rail PoE Switch'],
  'xd50':        ['Compact PoE Deployment', 'Single Cabinet Networking', 'Small Device Clusters', 'Edge PoE Switching'],
  'xf100':       ['Large IP Camera Deployments', 'Industrial Sensor Networks', 'High-Port-Count PoE', 'PoE Device Hub'],
  'xg82':        ['Managed Enterprise Networks', 'VLAN Segmentation', 'QoS-Critical Applications', 'IT/OT Convergence'],
  'pc3xx':       ['Legacy RS485 Integration', 'Modbus TCP Conversion', 'SCADA Serial-to-IP Bridge', 'Industrial Protocol Gateway'],
  'mcx':         ['Long-Distance Fiber Link', 'Building-to-Building Network', 'Campus Fiber Extension', 'Fiber Backhaul'],
  'rn50pcba':    ['Vehicle / Rolling Stock Networking', 'Embedded System Integration', 'Harsh Environment Deployment', 'M12 Ruggedized Networks'],
  'rvw50':       ['Railcar / Train Wi-Fi', 'Agricultural Machinery', 'Marine / Vessel Networking', 'Military Vehicle Comms'],
  'nms':         ['ISP Router Management', 'Smart City IoT Gateways', 'Enterprise Network Monitoring', 'Energy & Infrastructure Remote Sites'],
  'miniups':     ['Router Power Backup', 'Industrial Device Continuity', 'Remote Site Power Resilience', 'Gateway Failover Power'],
  'multimeter':  ['Energy Auditing', 'Building Energy Management', 'Industrial Power Monitoring', 'Utility Sub-metering'],
  'dcmeter':     ['Solar PV Monitoring', 'Battery System Monitoring', 'DC Plant Energy Metering', 'Telecom Power Monitoring'],
  'acmeter':     ['AC Distribution Monitoring', 'Motor Current Monitoring', 'Power Quality Analysis', 'Generator Output Metering'],
  'bcpmeter':    ['Panel-Level Energy Sub-metering', 'Data Center PDU Monitoring', 'Building Electrical Audit', 'Branch Circuit Monitoring'],
};

// Per-variant datasheets keyed by the exact part-number string from the last
// column of a variants table row (after stripping any parenthetical note).
const PART_DATASHEETS = {
  // RTS series
  'RTS00':   'assets/datasheets/RTS00-6.pdf',
  'RTS04-1': 'assets/datasheets/RTS04-1.pdf',
  'RTS04-2': 'assets/datasheets/RTS04-2.pdf',
  'RTS05-1': 'assets/datasheets/RTS05-1.pdf',
  'RTS05-2': 'assets/datasheets/RTS05-2.pdf',
  'RTS-60':  'assets/datasheets/RTS60.pdf',
  'RTS64-2': 'assets/datasheets/RTS64-2.pdf',
  'RTS65-1': 'assets/datasheets/RTS65-1.pdf',
  'RTS65-2': 'assets/datasheets/RTS65-2.pdf',
  // RU
  'RU60': 'assets/datasheets/RU60.pdf',
  // RO series
  'RO64-1': 'assets/datasheets/RO64-1.pdf',
  'RO64-2': 'assets/datasheets/RO64-2.pdf',
  'RO65-1': 'assets/datasheets/RO65-1.pdf',
  'RO65-2': 'assets/datasheets/RO65-2.pdf',
  // RT series
  'RT00':   'assets/datasheets/RT00.pdf',
  'RT04-1': 'assets/datasheets/RT04-1.pdf',
  'RT04-2': 'assets/datasheets/RT04-2.pdf',
  'RT05-1': 'assets/datasheets/RT05-1.pdf',
  'RT05-2': 'assets/datasheets/RT05-2.pdf',
  'RT-60':  'assets/datasheets/RT60.pdf',
  'RT64-1': 'assets/datasheets/RT64-1.pdf',
  'RT64-2': 'assets/datasheets/RT64-2.pdf',
  'RT65-1': 'assets/datasheets/RT65-1.pdf',
  'RT65-2': 'assets/datasheets/RT65-2.pdf',
  // RV series
  'RV04-1': 'assets/datasheets/RV04-1.pdf',
  'RV04-2': 'assets/datasheets/RV04-2.pdf',
  'RV50':   'assets/datasheets/RV50.pdf',
  'RV54-1': 'assets/datasheets/RV54-1.pdf',
  'RV54-2': 'assets/datasheets/RV54-2.pdf',
  'RV00':   'assets/datasheets/RV00.pdf',
  // RD series  ('RD44-A' in table → RD44.pdf is the matching family file)
  'RD44-A': 'assets/datasheets/RD44.pdf',
  'RD04-A': 'assets/datasheets/RD04-A.pdf',
  'RD44-B': 'assets/datasheets/RD44-B.pdf',
  'RD04-B': 'assets/datasheets/RD04-B.pdf',
  'RD44-C': 'assets/datasheets/RD44-C.pdf',
  'RD04-C': 'assets/datasheets/RD04-C.pdf',
  'RDS00':  'assets/datasheets/RDS00.pdf',
  // RE series
  'RE44': 'assets/datasheets/RE44.pdf',
  'RE04': 'assets/datasheets/RE04.pdf',
  // RI
  'RI44': 'assets/datasheets/RI44.pdf',
  // ODU
  'MT7621-01 ODU': 'assets/datasheets/ODU-MT7621.pdf',
  // IE series  (table uses "IE44-A", file uses "IE44A" — handled via key)
  'IE44-A':     'assets/datasheets/IE44A.pdf',
  'IE44-C':     'assets/datasheets/IE44C.pdf',
  'IE44-A-EX1': 'assets/datasheets/IE44A-EX1.pdf',
  // IA series
  'IA40-C': 'assets/datasheets/IA40-C.pdf',
  'IA44-A': 'assets/datasheets/IA44-A.pdf',
  'IA44-B': 'assets/datasheets/IA44-B.pdf',
  'IA44-C': 'assets/datasheets/IA44-C.pdf',
  // RFN series
  'RFN44-A': 'assets/datasheets/RFN44-A.pdf',
  'RFN44-B': 'assets/datasheets/RFN44-B.pdf',
  'RFN44-C': 'assets/datasheets/RFN44-C.pdf',
  // IAB series
  'IAB44-C': 'assets/datasheets/IAB44-C.pdf',
  'IAB44-B': 'assets/datasheets/IAB44-B.pdf',
  'IAB04-C': 'assets/datasheets/IAB04-C.pdf',
  // IAC series
  'IAC44-C': 'assets/datasheets/IAC44-C.pdf',
  'IAC44-A': 'assets/datasheets/IAC44-A.pdf',
  'IAC04-A': 'assets/datasheets/IAC04-A.pdf',
  'IAC04-C': 'assets/datasheets/IAC04-C.pdf',
  // IAF series
  'IAF44-C1': 'assets/datasheets/IAF44-C1.pdf',
  'IAF04-C1': 'assets/datasheets/IAF04-C1.pdf',
  // IDF series (-48V)
  'IDF04': 'assets/datasheets/IDF04.pdf',
  'IDF44': 'assets/datasheets/IDF44.pdf',
  'IDF54': 'assets/datasheets/IDF54.pdf',
  'IDF05': 'assets/datasheets/IDF05.pdf',
  'IDF45': 'assets/datasheets/IDF45.pdf',
  'IDF55': 'assets/datasheets/IDF55.pdf',
  // ID series (shared by idxx 9-30V products)
  'ID54':   'assets/datasheets/ID54.pdf',
  'ID54-B': 'assets/datasheets/ID54-B.pdf',
  'ID55':   'assets/datasheets/ID55.pdf',
  'ID55-B': 'assets/datasheets/ID55-B.pdf',
  // IDB series
  'IDB54': 'assets/datasheets/IDB54 (1).pdf',
  'IDB55': 'assets/datasheets/IDB55.pdf',
  // iSense
  'iSense Violet Plus Pro': 'assets/datasheets/Isense Violet Plus Pro.pdf',
  'iSense Green Plus Pro':  'assets/datasheets/Isense Green Plus Pro.pdf',
  'iSense Blue Plus Pro':   'assets/datasheets/Isense Blue Plus Pro.pdf',
  // Switches (full part-number string as it appears in the table)
  'XA82-2 Unmanaged PoE Switch':             'assets/datasheets/XA-82-2.pdf',
  'XB82-2 Unmanaged PoE Switch':             'assets/datasheets/XB-82-2.pdf',
  'XC-80-1 Unmanaged PoE Switch':            'assets/datasheets/XC-80-1.pdf',
  'XD50-1 Unmanaged PoE Switch':             'assets/datasheets/XD-50-1.pdf',
  'XF-100-1 Unmanaged PoE Switch':           'assets/datasheets/XF-100-1.pdf',
  'XG82-2L Gigabit Ethernet Managed Switch': 'assets/datasheets/XG-82-2L Updated.pdf',
  // PC3xx series
  'PC310': 'assets/datasheets/PC310.pdf',
  'PC311': 'assets/datasheets/PC311.pdf',
  'PC312': 'assets/datasheets/PC312.pdf',
};

// Product-level (family) datasheets for products that have no per-variant sheets
// or no variants table at all. Shown as a dedicated download bar in the modal.
const PRODUCT_DATASHEETS = {
  'intel-x6425': 'assets/datasheets/Intel X6425 Based Industrial PC.pdf',
  'inv-ce-xx':   'assets/datasheets/Intel X7425E SDWAN Box.pdf',
  'inv-cea-xx':  'assets/datasheets/Brief Specs Intel X7425E Alder Lake Industrial Automation PC (2) (1).pdf',
  'inv-ceb-xx':  'assets/datasheets/Intel X7425E Alder Lake 6 port SDWAN Box.pdf',
  'inv-cd-xx':   'assets/datasheets/INV-CD-N350_Datasheet.pdf',
  'multimeter':  'assets/datasheets/INV 4640 MFM.pdf',
  'dcmeter':     'assets/datasheets/ET1641 DC Meter.pdf',
  'acmeter':     'assets/datasheets/ET4602 AC Meter.pdf',
  'bcpmeter':    'assets/datasheets/ET7022 BCPM.pdf',
  'mcx':         'assets/datasheets/MC-1.pdf',
  'miniups':     'assets/datasheets/Mini UPS_Metal Enclosure_Datasheet 1.pdf',
  'rn50pcba':    'assets/datasheets/RN50.pdf',
};
